# Generated by Django 5.1.7 on 2025-03-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0002_alter_lignecommande_prix_unitaire_alter_panier_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Les groupes auxquels appartient cet utilisateur.', related_name='shop_utilisateur_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Les permissions spécifiques à cet utilisateur.', related_name='shop_utilisateur_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
