# Generated by Django 5.1.7 on 2025-03-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_lignecommande_prix_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='montant',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
