# Generated by Django 5.1.7 on 2025-03-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_payment_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stock_updated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
