# Generated by Django 5.1.7 on 2025-03-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='montant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
